FRIENDS = {
    "Snackburr": "ʕ •ᴥ•ʔ <",
    "Pancakes": "₍⸍⸌̣ʷ̣̫⸍̣⸌₎ <",
    "Mr Pickles": "(=｀ェ´=) <",
    "Satin": "▼・ᴥ・▼ <",
    "Thunky": "ᘛ⁐̤ᕐᐷ <",
    "Jingle": "꒰∗'꒳'꒱ <",
    "FluffButt": r"/ᐠ｡ꞈ｡ᐟ\ <",
    "Staplefoot": "(￣(エ)￣) <",
}


SNACKBURR_PHRASES = {
    "SNACKTIME": [
        "It's snack time!",
        "I'm back with s'more snacks! Who wants!?",
        "I'm back errbody! Who wants some snacks!?",
        "Woo man those errands are crazy! Anyways, anybody want some snacks?",
        "I got snacks! If nobody wants em, I'm gonna eat em all!!",
        "Hey, I'm back! Anybody in the mood for some snacks?!",
        "Heyyaaayayyyaya! I say Hey, I got snacks!",
        "Heyyaaayayyyaya! I say Hey, What's goin on?... I uh.. I got snacks.",
        "If anybody has reason why these snacks and my belly should not be wed, speak now or forever hold your peace!",
        "Got another snack delivery guys!",
        "Did somebody say snacks?!?! o/",
        "Choo Choo! it's the pb train! Come on over guys!",
        "Snacks are here! Dig in! Who wants a plate?",
        "Pstt.. I got the snacks you were lookin for. <.<",
        "I hope you guys are hungry! Cause i'm loaded to the brim with snacks!!!",
        "I was hungry on the way over so I kinda started without you guys :3 Who wants snacks!?!",
        "Beep beep! I got a snack delivery comin in! Who wants snacks!",
        "Guess what time it is?! It's snacktime!! Who wants?!",
        "Hey check out this sweet stach o' snacks I found! Who wants a cut?",
        "Who's ready to gobble down some snacks!?",
        "So who's gonna help me eat all these snacks? :3",
        "Eyoooooooo I haz snacks! Yall wanna munch???",
    ],
    "OUT": [
        "I'm out of snacks! I'll be back with more soon.",
        "I'm out of snacks :( I'll be back soon with more!",
        "Aight, I gotta head out! I'll be back with more, don worry :3",
        "Alright, I gotta get back to my errands. I'll see you guys soon!",
        "Uh okays, imma get back to my errands cuz outta snacks!",
        "Yall are cool but i gotta get back to my errands. I'll visit again soon!",
        "Errands call! Thanks for the help with eating all these snacks, I'll come again :3",
        "I have to go back do my stuffs, but as soon as I get more snacks imma come and share!!!",
    ],
    "LONELY": ["I guess you guys don't like snacktimes.. I'll stop comin around."],
    "NO_TAKERS": [
        "I guess nobody wants snacks... more for me!",
        "Guess nobody's here.. I'll just head out then",
        "I don't see anybody.. <.< ... >.> ... All the snacks for me!!",
        "I guess nobody wants snacks huh.. Well, I'll come back later",
        "I guess i'll just come back later..",
        "Well. Since yall dun want snacks imma eat them all!!!",
        "Where is everyone, I brought so many snacks...",
        "I did offer to share, but I guess you dun want. Oh well, I'll come back later :3",
        "Whoa... you dun wanna have any snacks?!",
        "I'll just eat all those snacks by myself then!",
        ":3 okay, catch yall lata",
    ],
    "GIVE": [
        "Here ya go, {0}, here's {1} pb!",
        "Alright here ya go, {0}, {1} pb for you!",
        "Yeah! Here you go, {0}! {1} pb!",
        "Of course {0}! Here's {1} pb!",
        "Ok {0}, here's {1} pb for you. Anyone else want some?",
        "Alllright, {1} pb for {0}!",
        "Hold your horses {0}! Alright, {1} pb for you :)",
        "Woooooooooo hey {0}, here have {1} pb!",
        "Here's {1} pb for {0} :3",
        "Heyheyehy hiya {0}! Here's {1} pb for you!",
        "Oh hiya {0} :) imma give you {1} pb now!",
        "Heyyyyyyyyyyy {0}, I brought you {1} pb :)",
        "Oh you wanna munchies? I have munchies for you, {0}! Have {1} pb :)",
        "{1} pb for {0}!!!",
        "{0} {0} {0}! Grab {1} pb!",
    ],
    "LAST_SECOND": [
        "Fine fine, {0}, I'll give you {1} of my on-the-road pb.. Cya!",
        "Oh! {0}, you caught me right before I left! Alright, i'll give you {1} of my own pb",
    ],
    "GREEDY": [
        "Don't be greedy now! you already got some pb {0}!",
        "You already got your snacks {0}!",
        "Come on {0}, you already got your snacks! We gotta make sure there's some for errbody!",
        "But! {0} you already had a bunch of snacks!",
        "Hey {0}, there must be snacks for others too!!",
        "Donot be like that, {0}, I wanna give snacks to errybody!",
        "Aw but {0}, we gonna run outta snacks if I give you again :(",
        "Let's make a deal, remind me when I come back from my errands next time, {0} :3",
        "Next time I'm comin 'round imma give you again, {0}",
        "I alredy handed you snacks {0}...",
        "But... but... you... you had your snacks {0} ._.",
        "I wanna give snacks to errybody! You can't have them all, {0}!",
        "You already munched on some snacks, {0}!",
        "Did you already gobble down yours, {0}? Gotta leave some for the others!",
    ],
    "EAT_BEFORE": [
        "monstrously",
        "shyly",
        "earnestly",
        "eagerly",
        "enthusiastically",
        "ravenously",
        "delicately",
        "daintily",
    ],
    "EAT_AFTER": [
        "gobbles up",
        "pigs out on",
        "wolfs down",
        "chows down",
        "munches on",
        "chugs",
        "puts away",
        "ravages",
        "siphons into their mouth",
        "disposes of",
        "swallows",
        "chomps",
        "consumes",
        "demolishes",
        "partakes of",
        "ingests",
    ],
    "ENABLE": ["Oh you guys want snacks?! Aight, I'll come around every so often to hand some out!"],
    "DISABLE": ["You guys don't want snacks anymore? Alright, I'll stop comin around."],
}
